### ISSUE TITLE
No receiver devices found

### ISSUE THREAD

**Issue by 424344** [hensm/fx_cast#199]
Hello,
I configured fx_cast on windows10.
when I try to cast it prints "No receiver devices found":
![image](https://user-images.githubusercontent.com/26486758/159246401-ac4d1466-1468-4e5f-8908-38aadb59bd9b.png)

this is the console of firefox:
![image](https://user-images.githubusercontent.com/26486758/159246440-e3ee23e5-7079-4764-b23e-a4f4a460604c.png)

**Comment by GameKyuubi** [comment]
I'm getting the same thing, even tho `mkchromecast` can find the device.

**Comment by kaizennet** [comment]
Same issue here.  Chromecast device is detected normally through Chrome browser.   Greatly looking forward to utilizing this project to cast through Firefox but continually get "No receiver devices found"

From browser console

![image](https://user-images.githubusercontent.com/103011545/161663578-7c19a81a-e66d-4b02-b9fb-0c836fbe7efd.png)

Please let me know if there is anything else useful i can provide to assist troubleshooting.   From my Windows device.  My Chromecast model is fairly ancient, possibly even 1st gen.  Still working OK though for our needs.

Thank you.

**Comment by hensm** [comment]
This has _probably_ been fixed on the master branch for a while unless it's caused by something else. Just, there's some regressions from a while back that I haven't had time to sort out that make me reluctant to push a new release.

@kaizennet
If you want to test, here's an unsigned release of the latest commit: [fx_cast-0.2.0-alpha.zip](https://github.com/hensm/fx_cast/files/8498865/fx_cast-0.2.0-alpha.zip)  
https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ

**Comment by hensm** [comment]
Well, figured now was as good a time as ever, so spent a little while debugging and fixing those regressions. 200,000-line obfuscated Netflix/YouTube scripts are such a pain 😓. I'll probably push a new release in the next few days.

Will close if fixed after then.

**Comment by 424344** [comment]
Hello, thanks for the new version. I've tried 0.20 and it fixes the issue with no receivers found (tested on youtube)
Unfortunately the "cast" button is disabled. Will investigate later.

**Comment by hensm** [comment]
Just to confirm, is YouTube whitelisted (toolbar button context menu → `Add to Whitelist`) and are you using the cast button in the YouTube player?

Side note: Looks as though initiating casting from the toolbar button is broken again, so that's another thing to fix.

**Comment by 424344** [comment]
I played with the options, reloader the page, restarted the browser.... and now it seems to work.
It's not clear what  I have done to make it work.
But in the options I saw the app id... what is it? Do I need to change it?
I have read about a different app id for youtube ( 233637DE ) here:
https://github.com/hensm/fx_cast-compat/issues/10
Do I need to change it? How can I find the app ids for different sites?
Thanks.

**Comment by hensm** [comment]
No, that's for screen mirroring, it probably shouldn't ever be changed. Sites provide their own app IDs to the extension, so there's no need to manually enter them.

**Comment by hensm** [comment]
Should be fixed in the latest release.

**Comment by kaizennet** [comment]
@hensm sorry to comment on an already closed case and that it took so long to response.  I'm still unable to cast successfully but definitely a big improvement and this exact reported issue is resolved.   After upgrading the fx_cast and the bridge to 0.2.0 our device now shows up in the list!     When I click "Cast" (using the Tab feature) nothing actually happens, actually it turns the TV being casted to black.    I will try to search for existing open issue request to cover this or submit a new one.    

Thanks for the response and work!

**Comment by hensm** [comment]
@kaizennet 
Is that just a problem with the tab/screen sharing or does it affect regular apps like YouTube/Netflix?

**Comment by 424344** [comment]
> it turns the TV being casted to black

my TV sometimes turns black and shows a little blue icon at the center of the screen. Is the same for you or your screen is completely black?

**Comment by kaizennet** [comment]
Apology again for the delay in response.  Since that one promising time when the casting device appeared in the list it has since not shown up again.  Therefore I'm unable to get to the point to see it YouTube (canceled NF a while back) steaming is possible.     That one time the screen was completely black though almost as if the TV was completely off. 

I was hoping I could get back to the point where the device even showed in the list again.   Tried multiple restarts of pc, browser, the chromecast device itself, reinstalling fx_cast and the bridge a few times.   The Chromecast device appears as normal in Chrome browser and we can use it to stream, so i'm somewhat certain it's not a device or local network issue.    

On YouTube the app option correctly appears in the fx_cast list above Tab + Screen options but there is no corresponding device to select.   No immediate errors are apparent in the console

![image](https://user-images.githubusercontent.com/103011545/164998994-a5a587ea-6acc-4be2-8203-44c941795a02.png)

I'll keep an eye out for new version releases and keep trying.  Thanks for your reply.
